### ISSUE TITLE
Project doesn't install with Node 12

### ISSUE THREAD

**Issue by macintacos** [prometheas/jira-2-omnifocus#24]
It was worth a shot, but this project doesn't compile with Node 12.13.1 (I mean, considering that it's been a while since the last commit, I think that's to be expected). Here's the error I got when running `npm install`:

```
1 error generated.
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/juliant/GitLocal/Play/jira-2-omnifocus/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/juliant/.n/bin/node" "/Users/juliant/GitLocal/Play/jira-2-omnifocus/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/juliant/GitLocal/Play/jira-2-omnifocus/node_modules/node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juliant/.npm/_logs/2020-08-04T17_18_28_697Z-debug.log
```

Versions I had at the time when I ran it:

```
 I => npm --version
6.14.4
 I => node --version
v12.13.0
```

I switched to the latest version of Node 8 (the latest version in 2017 it seems) and the project built fine. I'm wondering if we just need to upgrade dependencies, but that might just bring its own set of problems.

I am mostly opening this because I was going to look into how difficult it'd be to diagnose #23 and maybe open a PR to fix it.

**Comment by prometheas** [comment]
I've learned that this was due to the Sass dependency, which seems to compile native code that links against the node binary (hence why the node version is relevant here). I've got just a hair more testing to do here, but this is looking like it'll be fixed in within the hour… (let's ignore that these are famous last words).
