### ISSUE TITLE
Button not appearing on issue page

### ISSUE THREAD

**Issue by shhQuiet** [prometheas/jira-2-omnifocus#9]
The URL of my issue is:
http://icommunity.dstcorp.net/jira/browse/PDX-1163

Any idea why the extension is not triggered?

FYI: No errors in the console that I see..

**Comment by prometheas** [comment]
I can't even resolve that host, let alone connect to the server… are you sure that hostname is available in public DNS?

**Comment by shhQuiet** [comment]
No, it is our company intranet.  I included the URL so you could see the pattern.

**Comment by prometheas** [comment]
Ah! I see, now. I'll try to look this weekend. Thanks for clarifying, @shhQuiet.

**Comment by dknighton** [comment]
I noticed this issue with my company's JIRA server as well, which is also an internal domain and not publicly available on the Internet. For what it's worth, I'd love to see the ability for the plugin to work with private/enterprise JIRA instances as well. Thank you!

**Comment by prometheas** [comment]
I created this to work with my company's enterprise JIRA server, so it definitely works with them :)

The problem here is plugin assumes the JIRA service is installed at the host's root (the examples here both show a base path on the sample URL).

I will slate a fix for my next release.

**Comment by prometheas** [comment]
@dknighton, actually, my vacation brain somehow assumed you shared a URL… can you confirm whether your company's service uses the host's root, or whether it's mounted under a base path?

**Comment by prometheas** [comment]
@dknighton, bump :)

**Comment by prometheas** [comment]
OK, folks! I've got an attempted fix that I'd love some feedback on. I don't have access to a JIRA instance that uses a base path prefix, so I cannot myself validate the fix. Please test the fix by:

1. clone this repo
2. checking out the `feature/configurable-service-base-path` branch
3. go to chrome://extensions
4. disable whatever version of the JIRA to OmniFocus you might have presently installed
5. make sure the "Developer mode" checkbox is checked (top right)
6. click the "Load unpacked extension…" button (top left)
7. select the parent directory of the project you've cloned from Github

You should now see the extension with version of 1.1.2-rc1 installed and activated in Chrome. Please navigate to a JIRA task on your service and see if it properly works.

Looking forward to your feedback, @shhQuiet and @dknighton. If it looks good, I'll ship the update to the extension immediately.

**Comment by shhQuiet** [comment]
John: Mixed success...  I had to modify the version to 1.1.2.1 for Chrome to load it.  After that the button appeared on my Jira pages (yay!).

I configured it to use my maildrop address, but clicking the button gives me no feedback at all, success or failure?  I looked in the console and see nothing :(

**Comment by shhQuiet** [comment]
Ah, a little more info- it does seem to be working!  I opened the background window for the extension and when I click the button, I see a network request to my gmail server.  It isn't working for me because I can't use gmail behind corporate firewall, but I take responsibility for fixing that one.

I will try to configure chrome to use my Outlook mail for mailto: here at work and try it again tomorrow...  Once I do that, I see no reason why it won't work... :) Thanks!

**Comment by prometheas** [comment]
Thanks for your lightning fast response, @shhQuiet!

I had realized the invalid version string (I got a bit too clever for myself), and have changed the version string to 1.1.2 (also updated my previous comment to reflect that a few minutes ago).

Back to your feedback:

Thanks for confirming the appearance of the button on pages! Maildrop seems to be working properly on my machine, so I'm going to resolve this issue. I'll hang on until tomorrow to ship a new version of the extension, just in case you manage to find some weird edge case I'm not triggering. Though given the actual diff of this branch from master, I'm very optimistic we've nailed this.

**Comment by shhQuiet** [comment]
John, just confirming that the extension is working properly.  I configured mailto: links to use Outlook and clicking the link brings up a new mail window filled out with the details of the issue.  Looks great- I hope to use this quite a bit to move issues to OF...

Thanks for the fix, looking forward to the release.

**Comment by prometheas** [comment]
Nice one. Preparing the new release today.

**Comment by prometheas** [comment]
@shhQuiet and @dknighton, I've just published 1.1.2. According to the the Chrome Web Store developer portal, the update ought to be available in the next hour or so.

Thanks again for your feedback and assistance.
